name: Daily News Job

on:
  schedule:
    - cron: "15 9 * * *"
  workflow_dispatch:

jobs:
  run-news-script:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: ${{ DBPASS.DB_USER }}        # map DB_USER to POSTGRES_USER
          POSTGRES_PASSWORD: ${{ DBPASS.DB_PASSWORD }} # map DB_PASSWORD to POSTGRES_PASSWORD
          POSTGRES_DB: ${{ DBPASS.DB_NAME }}           # map DB_NAME to POSTGRES_DB
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U ${{ DBPASS.DB_USER }}"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run news script
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: ${{ DBPASS.DB_USER }}
          DB_PASSWORD: ${{ DBPASS.DB_PASSWORD }}
          DB_NAME: ${{ DBPASS.DB_NAME }}
          API_KEY: ${{ DBPASS.API_KEY }}
        run: python scripts/load_to_db.py
