name: Daily News Job

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  run-news-script:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run news script
        run: newsapi/scripts/load_to_db.py
