name: Daily News Job
on:
  schedule:
    - cron: "55 9 * * *"
  workflow_dispatch:
jobs:
  run-news-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Create .env file
        run: echo "${{ secrets.CONFIG }}" > .env
      - name: Run news script
        run: python scripts/load_to_db.py